apiVersion: v1
kind: StorageClass
metadata:
  name: kube-aws-gp3-storage
provisioner: ebs-csi-aws.com
volumeBindingMode: WaitForFirstCustomer
reclaimPolicy: Delete
allowVolumeExpansion: True
parameters:
  type: gp3 
