apiVersion: v1
kind: StorageClass
metadata:
  name: kube-aws-gp3-storage
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: gp3 
