replicaCount: 1

namespace: mcp-server

serviceAccount:
  create: false
  name: mcp-server

podSecurityContext: {}

podAnnotations: {}

autoscaling:
  enabled: false

containers:
  - name: mcp-server
    image: nishank840/kube-helm-mcp:latest
    pullPolicy: Always
    port: 8000
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: mcp-github-token
            key: GITHUB_TOKEN
      - name: JIRA_URL
        valueFrom:
          secretKeyRef:
            name: mcp-jira-secret
            key: JIRA_URL
      - name: JIRA_EMAIL
        valueFrom:
          secretKeyRef:
            name: mcp-jira-secret
            key: JIRA_EMAIL
      - name: JIRA_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: mcp-jira-secret
            key: JIRA_API_TOKEN
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
