apiVersion: v1
kind: Service
metadata:
  name: mcp-server-svc
  namespace: mcp-server
spec:
  selector:
    app.kubernetes.io/instance: mcp-server
    app.kubernetes.io/name: app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082
  type: NodePort
