apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: order-service
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: order-service
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
