apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: payment-service
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: payment-service
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
