apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-app
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: python-app  
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
