apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
  name: nodejs-app-pvc
  namespace: nodejs-app
  labels:
    color: green
    language: nodejs
spec:
  accessModes: ReadWriteOnce
sotrageClass: kube-aws-gp3-storage
resources:
  requests:
    storage: 1Gi
