apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-api-pvc
  namespace: auth-api
  labels:
    language: java
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kube-aws-gp3-storage
  resources:
    requests:
      storage: 1Gi
