apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-service-pvc
  namespace: payment-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kube-aws-gp3-storage
  resources:
    requests:
      storage: 1Gi
