apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-pvc
  namespace: python-app
  labels:
    color: blue
    language: python
spec:
  accessModes: 
    - ReadWriteOnce
storageClass: kube-aws-gp3-storage
resources:
  requests:
    storage: 1Gi

