replicaCount: 1

#namespace
namespace: python-app

persistence:
  enabled: true
  claimName: python-app-pvc
  mountPath: /data

containers:
  - name: python-app
    image: nginx:latest
    port: 80
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
    volumeMounts:
      - name: app-storage
        mountPath: /app/data

  - name: mysql
    image: mysql:8.0
    port: 3306
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: rootpassword

volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: python-app-pvc
