replicaCount: 1

namespace: mcp-server-ui

persistence:
  enabled: true
  claimName: mcp-server-ui-pvc
  mountPath: /data

containers:
  - name: mcp-server-ui
    image: nginx:latest
    port: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    volumeMounts:
      - name: app-storage
        mountPath: /app/data

volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: mcp-server-ui-pvc
